CREATE USER 'postgres'@'localhost' IDENTIFIED BY 'postgres';

GRANT ALL PRIVILEGES ON * . * TO 'postgres'@'localhost';

CREATE DATABASE first_db;
USE first_db;

CREATE TABLE Person (
                        user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(100) NOT NULL,
                        age int CHECK (age > 0),
                        email varchar UNIQUE,
                        address VARCHAR NOT NULL
);

INSERT INTO Person (name, age, email, address)
VALUES
    ('Tom', 18, 'tom@gmail.com', 'some address'),
    ('Bob', 28, 'bob@gmail.com', 'some address'),
    ('Stiv', 38, 'stiv@gmail.com', 'some address'),
    ('Edisson', 48, 'edisson@gmail.com', 'some address');

-- SELECT * FROM person;
--
-- TRUNCATE TABLE Person;
-- ALTER TABLE Person ADD COLUMN address VARCHAR NOT NULL;
-- DROP TABLE person;
--
-- CREATE SEQUENCE first_sequence;
--
-- SELECT NEXTVAL('first_sequence');
--
-- DROP SEQUENCE public.first_sequence;