DROP TABLE IF EXISTS Person;

CREATE TABLE Person(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100),
    age int
);

INSERT INTO Person(id, name, age)
VALUES (1, 'Test person', 20);

TRUNCATE TABLE Person;

ALTER TABLE Person ADD COLUMN email VARCHAR(100) UNIQUE;

-- Просто дата без точного времени
ALTER TABLE Person ADD COLUMN date_of_birth DATE;

-- Точное время
-- В PostgreSQL значение timestamp сохраняются в секундах до или после полуночи 1 января 2000 г.
ALTER TABLE Person ADD COLUMN created_at TIMESTAMP;

SELECT * FROM Person;

-- CREATE SEQUENCE person_id_seq;

CREATE TABLE Item(
                       id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       person_id int REFERENCES Person(id),
                       item_name varchar(100)
);