app.services.greeting.message: Hello World

spring:
  datasource:
    username: postgres
    password: Invest12!
    url: jdbc:postgresql://localhost:5432/company
    driver-class-name: org.postgresql.Driver

  # V(version)__description.sql
  flyway:
    baseline-on-migrate: true
