DROP TABLE IF EXISTS Sensor CASCADE ;

CREATE TABLE Sensor (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30)  NOT NULL UNIQUE
);

DROP TABLE IF EXISTS Measurement;

CREATE TABLE Measurement (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        value DECIMAL,
                        raining BOOLEAN,
                        measurement_date_time TIMESTAMP,
                        sensor VARCHAR(30) REFERENCES Sensor(name) ON DELETE NO ACTION ON UPDATE NO ACTION
);

SELECT * FROM Sensor;
SELECT * FROM Measurement;

TRUNCATE TABLE Sensor;
TRUNCATE TABLE Measurement;
