/*
 * This file is generated by jOOQ.
 */
package com.demo.jooq.domain;


import com.demo.jooq.domain.tables.Comments;
import com.demo.jooq.domain.tables.Posts;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.COMMENTS</code>.
     */
    public static final Comments COMMENTS = Comments.COMMENTS;

    /**
     * The table <code>PUBLIC.POSTS</code>.
     */
    public static final Posts POSTS = Posts.POSTS;
}
