DROP TABLE IF EXISTS Person;

CREATE TABLE Person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(100) NOT NULL UNIQUE,
    year_of_birth int NOT NULL CHECK(year_of_birth >= 1900),
    password varchar NOT NULL
                    );

INSERT INTO Person (username, year_of_birth, "password")
VALUES ('test_user_1', 1960, 'test_password'),
       ('test_user_2', 1960, 'test_password');

SELECT * FROM Person;
